In [11]:
import pandas_datareader as pdr
import pandas as pd
import datetime

In [12]:
start_date = datetime.datetime(1989, 5, 1)
end_date = datetime.datetime(2024, 12, 31)

In [13]:
indicators = {
    'Unemployment': 'UNRATE',
    'Real GDP': 'GDPC1',
    'Inflation': 'CORESTICKM159SFRBATL',
    '10-3 Yield Curve': 'T10Y3M'
}

dataframes = {}

for name, code in indicators.items():
    dataframes[name] = pdr.get_data_fred(code, start=start_date, end=end_date)
    
df = pd.concat(dataframes, axis=1)
df

           Unemployment Real GDP            Inflation 10-3 Yield Curve
                 UNRATE    GDPC1 CORESTICKM159SFRBATL           T10Y3M
DATE
1989-05-01          5.2      NaN             4.742748             0.20
1989-05-02          NaN      NaN                  NaN             0.19
1989-05-03          NaN      NaN                  NaN             0.22
1989-05-04          NaN      NaN                  NaN             0.22
1989-05-05          NaN      NaN                  NaN             0.26
...                 ...      ...                  ...              ...
2024-06-26          NaN      NaN                  NaN            -1.18
2024-06-27          NaN      NaN                  NaN            -1.20
2024-06-28          NaN      NaN                  NaN            -1.12
2024-07-01          NaN      NaN                  NaN            -0.99
2024-07-02          NaN      NaN                  NaN            -1.04

[9295 rows x 4 columns]

In [14]:
df.isnull().sum()

Unemployment      UNRATE                  8874
Real GDP          GDPC1                   9156
Inflation         CORESTICKM159SFRBATL    8874
10-3 Yield Curve  T10Y3M                   494
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9295 entries, 1989-05-01 to 2024-07-02
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   (Unemployment, UNRATE)             421 non-null    float64
 1   (Real GDP, GDPC1)                  139 non-null    float64
 2   (Inflation, CORESTICKM159SFRBATL)  421 non-null    float64
 3   (10-3 Yield Curve, T10Y3M)         8801 non-null   float64
dtypes: float64(4)
memory usage: 363.1 KB

In [17]:
df.columns = [' '.join(col).strip() for col in df.columns.values]

df.rename(columns={'DATE':'Date'}, inplace=True)


df.to_csv('FRED_data.csv', index=False)

In [18]:
df

,U n e m p l o y m e n t U N R A T E,R e a l G D P G D P C 1,I n f l a t i o n C O R E S T I C K M 1 5 9 S F R B A T L,1 0 - 3 Y i e l d C u r v e T 1 0 Y 3 M
DATE,,,,
1989-05-01,5.2,NaN,4.742748,0.20
1989-05-02,NaN,NaN,NaN,0.19
1989-05-03,NaN,NaN,NaN,0.22
1989-05-04,NaN,NaN,NaN,0.22
1989-05-05,NaN,NaN,NaN,0.26
...,...,...,...,...
2024-06-26,NaN,NaN,NaN,-1.18
2024-06-27,NaN,NaN,NaN,-1.20
2024-06-28,NaN,NaN,NaN,-1.12
2024-07-01,NaN,NaN,NaN,-0.99
2024-07-02,NaN,NaN,NaN,-1.04

In [19]:
df.duplicated().sum()

8306